require: rubocop-rails

# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*_helper.rb'
    - 'vendor/**/*'
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false # Default Rails files have comment lines this long
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false # Allow *%i[…]

Rails/HasAndBelongsToMany:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false # Don't require a class comment
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false # Allow but do not require
Style/Lambda:
  Enabled: false # The examples I see always use stabby lambdas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  Enabled: false
